# Generated by Django 4.2.30 on 2026-07-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subsector',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon', max_length=50, null=True),
        ),
    ]
