# Generated by Django 4.2.30 on 2026-08-14 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_useractivity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pdrbdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pdrbdata',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.province'),
        ),
        migrations.AlterUniqueTogether(
            name='pdrbdata',
            unique_together={('year', 'province', 'district', 'subsector')},
        ),
    ]
