# Generated by Django 4.2.30 on 2026-08-19 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pdrbdata_unique_together_pdrbdata_province_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productiondata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commodity',
            name='kelompok_utama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='subkelompok',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_data', to='api.district'),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_data', to='api.subdistrict'),
        ),
        migrations.AlterUniqueTogether(
            name='productiondata',
            unique_together={('year', 'district', 'subdistrict', 'commodity')},
        ),
    ]
