services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: petapotensi_backend
    ports:
      - "7031:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: petapotensi_frontend
    ports:
      - "1307:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://72.60.78.97:7031
      - API_URL=http://backend:8000
    command: sh -c "npm run build && npm start"
    depends_on:
      - backend
